[2023-03-07T17:25:19.746+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Ingest_to_Snowflake.create_circuits_table manual__2023-03-07T17:00:03.981621+00:00 [queued]>
[2023-03-07T17:25:19.855+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: Ingest_to_Snowflake.create_circuits_table manual__2023-03-07T17:00:03.981621+00:00 [queued]>
[2023-03-07T17:25:19.855+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-07T17:25:19.855+0000] {taskinstance.py:1280} INFO - Starting attempt 6 of 6
[2023-03-07T17:25:19.855+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-07T17:25:19.866+0000] {taskinstance.py:1300} INFO - Executing <Task(SnowflakeOperator): create_circuits_table> on 2023-03-07 17:00:03.981621+00:00
[2023-03-07T17:25:19.872+0000] {standard_task_runner.py:55} INFO - Started process 3159 to run task
[2023-03-07T17:25:19.874+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Ingest_to_Snowflake', 'create_circuits_table', 'manual__2023-03-07T17:00:03.981621+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/copy_into_snowflake.py', '--cfg-path', '/tmp/tmpvya9yo8o']
[2023-03-07T17:25:19.875+0000] {standard_task_runner.py:83} INFO - Job 102: Subtask create_circuits_table
[2023-03-07T17:25:19.914+0000] {task_command.py:388} INFO - Running <TaskInstance: Ingest_to_Snowflake.create_circuits_table manual__2023-03-07T17:00:03.981621+00:00 [running]> on host d7fd3210ba1e
[2023-03-07T17:25:19.964+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Ingest_to_Snowflake
AIRFLOW_CTX_TASK_ID=create_circuits_table
AIRFLOW_CTX_EXECUTION_DATE=2023-03-07T17:00:03.981621+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-07T17:00:03.981621+00:00
[2023-03-07T17:25:19.964+0000] {sql.py:254} INFO - Executing: ['sql/sql_statements.create_circuits_table', 'sql/sql_statements.start_warehouse']
[2023-03-07T17:25:19.969+0000] {base.py:73} INFO - Using connection ID 'snowflake_conn' for task execution.
[2023-03-07T17:25:20.135+0000] {base.py:73} INFO - Using connection ID 'snowflake_conn' for task execution.
[2023-03-07T17:25:20.136+0000] {connection.py:287} INFO - Snowflake Connector for Python Version: 3.0.1, Python Version: 3.7.16, Platform: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-debian-11.6
[2023-03-07T17:25:20.136+0000] {connection.py:990} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-03-07T17:25:20.136+0000] {connection.py:1007} INFO - Setting use_openssl_only mode to False
[2023-03-07T17:25:20.829+0000] {cursor.py:738} INFO - query: [ALTER SESSION SET autocommit=False]
[2023-03-07T17:25:20.902+0000] {cursor.py:751} INFO - query execution done
[2023-03-07T17:25:20.902+0000] {cursor.py:891} INFO - Number of results in first chunk: 1
[2023-03-07T17:25:20.902+0000] {sql.py:375} INFO - Running statement: sql/sql_statements.create_circuits_table, parameters: None
[2023-03-07T17:25:20.902+0000] {cursor.py:738} INFO - query: [sql/sql_statements.create_circuits_table]
[2023-03-07T17:25:20.980+0000] {cursor.py:751} INFO - query execution done
[2023-03-07T17:25:20.984+0000] {connection.py:586} INFO - closed
[2023-03-07T17:25:21.007+0000] {connection.py:589} INFO - No async queries seem to be running, deleting session
[2023-03-07T17:25:21.084+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 266, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 379, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/cursor.py", line 839, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 294, in errorhandler_wrapper
    error_value,
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.7/site-packages/snowflake/connector/errors.py", line 231, in default_errorhandler
    cursor=cursor,
snowflake.connector.errors.ProgrammingError: 001003 (42000): 01aaca75-0000-0ab4-0000-1e09000140be: SQL compilation error:
syntax error line 1 at position 0 unexpected 'sql'.
[2023-03-07T17:25:21.091+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=Ingest_to_Snowflake, task_id=create_circuits_table, execution_date=20230307T170003, start_date=20230307T172519, end_date=20230307T172521
[2023-03-07T17:25:21.102+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 102 for task create_circuits_table (001003 (42000): 01aaca75-0000-0ab4-0000-1e09000140be: SQL compilation error:
syntax error line 1 at position 0 unexpected 'sql'.; 3159)
[2023-03-07T17:25:21.128+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-07T17:25:21.147+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
