[2023-02-28T20:21:53.829+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: s3_upload_test.postgres_to_s3 manual__2023-02-28T20:21:52.503927+00:00 [queued]>
[2023-02-28T20:21:53.837+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: s3_upload_test.postgres_to_s3 manual__2023-02-28T20:21:52.503927+00:00 [queued]>
[2023-02-28T20:21:53.838+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-28T20:21:53.838+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 6
[2023-02-28T20:21:53.838+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-28T20:21:53.849+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2023-02-28 20:21:52.503927+00:00
[2023-02-28T20:21:53.854+0000] {standard_task_runner.py:55} INFO - Started process 2215 to run task
[2023-02-28T20:21:53.857+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 's3_upload_test', 'postgres_to_s3', 'manual__2023-02-28T20:21:52.503927+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/s3_upload_dag.py', '--cfg-path', '/tmp/tmpwpkceuad']
[2023-02-28T20:21:53.857+0000] {standard_task_runner.py:83} INFO - Job 58: Subtask postgres_to_s3
[2023-02-28T20:21:53.903+0000] {task_command.py:388} INFO - Running <TaskInstance: s3_upload_test.postgres_to_s3 manual__2023-02-28T20:21:52.503927+00:00 [running]> on host 2341ffaf5508
[2023-02-28T20:21:53.957+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=tem109
AIRFLOW_CTX_DAG_ID=s3_upload_test
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-02-28T20:21:52.503927+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-28T20:21:52.503927+00:00
[2023-02-28T20:21:53.965+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-02-28T20:21:53.980+0000] {s3_upload_dag.py:31} INFO - Saved orders data in text file: dags/get_orders_20230228.txt
[2023-02-28T20:21:54.072+0000] {base.py:73} INFO - Using connection ID 's3_conn' for task execution.
[2023-02-28T20:21:54.072+0000] {connection_wrapper.py:334} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from login and password.
[2023-02-28T20:21:54.824+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-02-28T20:21:54.834+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=s3_upload_test, task_id=postgres_to_s3, execution_date=20230228T202152, start_date=20230228T202153, end_date=20230228T202154
[2023-02-28T20:21:54.871+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-02-28T20:21:54.884+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
